### ISSUE TITLE
Random period

### ISSUE THREAD

**Issue by nickstienz** [Dhi13man/rust_text_editor#1]
https://github.com/Dhi13man/rust_text_editor/blob/4c585d722b437e0a10e9366744fca952a030389d/README.MD?plain=1#L29

I don’t know if this is intentional or not but there is a period here unlike any other bullet points!

Sorry for the small issue but I wanted to let you know.

**Comment by Dhi13man** [comment]
Fixed in latest commits. Thank you for bringing it to my attention. :)
